### ISSUE TITLE
Add another background image alongside the previous one

### ISSUE THREAD

**Issue by vvswps** [vvswps/fem-manage-landing-page#1]
### Add another pill shaped image in the background is the top right corner as in the picture below

![image](https://user-images.githubusercontent.com/20621664/178157085-aa818bb6-709a-46bf-b80f-c7a63ea28e05.png)

## Current

![image](https://user-images.githubusercontent.com/20621664/178157194-25f31b25-9195-4af2-8fe0-2448f2919d5e.png)

**Comment by vidhanshu** [comment]
assign this issue to me.
