### ISSUE TITLE
Styling cards (SwiperJs)

### ISSUE THREAD

**Issue by vvswps** [vvswps/fem-manage-landing-page#2]
### The image should be positioned on the top mid halfway through the card background like in the image below

![image](https://user-images.githubusercontent.com/20621664/178157305-aeab19d8-409f-45d0-97d0-8db1c8a4c313.png)

## Current 

![image](https://user-images.githubusercontent.com/20621664/178157318-6f275eb9-8b47-4e79-85c5-4056ce9968b4.png)

**Comment by vidhanshu** [comment]
assign this issue to me
